# Website info
name: 'Ivan Bajalović'
description: "Personal blog"

# Author's info
author: 'Ivan Bajalović'
username: bajalovic
bio: 'Partner at EsseWorks'
location: 'Belgrade, Serbia'
url: 'http://esseworks.com'
image: '/assets/images/me.jpg'

# Jykell configuration
markdown: redcarpet
highlighter: pygments
paginate: 5
language: 'en-uk'
short_url: 'bajalovic.github.io'
google_analytics: UA-69788637-1
disqus: 
baseurl: ''

# Permalinks
permalink: /:title
#permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...
