# Site settings
title: Ivan Bajalovic
email: ivan@esseworks.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bajalovic.github.io" # the base hostname & protocol for your site
twitter_username: ivanbajalovic
github_username: bajalovic

# Build settings
markdown: kramdown
